import Script from 'next/script'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <a href="#" id="creditclan-widget" className='hidden' >Apply on CreditClan</a>
      <Script src="https://appfive.creditclan.com/boot/client.js" strategy='beforeInteractive' />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
